open-io/rpm-specfiles

puppet-keepalived/puppet-keepalived.spec
base on https://forge.puppetlabs.com/arioch/keepalived
=> add puppet-keepalived spec

puppet-concat/puppet-concat.spec
=> First release of puppet concat

openio-sds-logrotate/openio-sds-logrotate.conf
=> add log rotation to account, oioproxy, oio-event-agent and rdir

python-diamond-openio/openiosds.py
Also copy uncommited modifications found on test servers.
=> python-diamond-openio: replace local listing by global+filter

openio-sds-logrotate/openio-sds-logrotate.conf, openio-sds-logrotate/openio-sds-logrotate.spec
Prevent state "Deleted" for log file during log rotate
=> Fix deleted file symptom for http-errors.log

openio-sds/openio-sds.spec
Add election python files in specfile.
=> Add election tool in oio-tool

mock-config-openio/mock-config-openio.spec
- Move license & readme to /usr/share
- More accurate file globbing
=> New version 17.04.0-3

oiofs-fuse/oiofs-fuse.spec
=> RPM packaging for oiofs

openstack-swift-plugin-swift3/openstack-swift-plugin-swift3.spec
=> Add unstable packaging

openio-gridinit/openio-gridinit-systemd.service
I think @dargor  validated these values on the QA
=> Modify the systemd unit for gridinit to increase limits

openio-sds-rsyslog/openio-sds-rsyslog.conf
```
[root@node3 sds]# find /var/log/oio/sds/ -type d -ls
515774    0 drwxr-x--x   3 openio   openio         20 Aug  7 10:57 /var/log/oio/sds/
48118623    0 drwxr-x---  11 openio   openio        176 Aug  7 15:28 /var/log/oio/sds/OPENIO
52312721    0 drwxr-x---   2 openio   openio         47 Aug  7 14:29 /var/log/oio/sds/OPENIO/meta1-1
519261    0 drwxr-x---   2 openio   openio         47 Aug  7 15:19 /var/log/oio/sds/OPENIO/meta0-1
5584458    0 drwxr-x---   2 openio   openio         47 Aug  7 10:57 /var/log/oio/sds/OPENIO/meta2-1
8483165    0 drwxr-x---   2 openio   openio         53 Aug  7 15:19 /var/log/oio/sds/OPENIO/oioproxy-1
48118624    0 drwxr-x---   2 openio   openio         36 Aug  7 11:00 /var/log/oio/sds/OPENIO/oio-blob-indexer-1
38427410    0 drwxr-x---   2 openio   openio …
```
=> Change rights on file and directory, Vulgarize regexp

openio-sds/openio-sds.spec
Add `oio-meta2-indexer` tool introduced in 4cdd1b8b7a06df5e4c93a9130703d36868872118
Add `oio-file-tool` tool introduced in 78c673a8f86dbc8ec713da92e53aad134cadc2a6
=> Add new binaries for 18.10

openio-gridinit/openio-gridinit-systemd.service
=> gridinit: Add TasksMax=infinity

openio-sds/openio-sds.spec
and move mover/indexer to server package instead of tools.
=> sds: add binaries

openio-sds/openio-sds.spec
Reverts open-io/rpm-specfiles#170
=> Revert "sds: add binaries"

openio-sds-replicator/openio-sds-replicator.spec
=> Replicator: new release 0.5.3

openio-sds/openio-sds.spec
Remove some deprecated tools
Add new binary
Add new golang dependency
=> Prepare 19.04

openio-netdata-plugins/openio-netdata-plugins.spec
- Add s3roundtrip plugin (using aws-sdk-go)
- Revert to 755 for all executables (now managed via netdata config)
=> Release 0.5.0 for openio-netdata-plugins

grafana/grafana.spec
Related: https://github.com/open-io/rpm-specfiles/pull/199
=> Add grafana specfile

alertmanager/alertmanager.default, alertmanager/alertmanager.service
All options should remain in the defaults file
=> Alertmanager: Remove hardcoded values from packaged systemd unit
